name = "BlaSwitch"
uuid = "e9d9abad-1fb7-461a-8d1e-eeb0727d2838"
authors = ["RuQing Xu <r-xu@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[compat]
PackageCompiler = "1"
